### ISSUE TITLE
Dotplots with fold changes and LTSR

### ISSUE THREAD

**Issue by ccruizm** [elo073/5loclung#1]
Hello @elo073!

I like how you summarize certain variables' effects with the LTSR and the fold change. How do you get the LTSR, and could you share an example code for generating such nice plots, please? 

Many thanks for considering my request.

**Comment by elo073** [comment]
Hi!

I'm afraid I don't have the code anymore as left it with the institute. You
could ask Amanda Oliver whether she still has them ***@***.***), or
directly from Natsuhiko Kumasaka (https://github.com/natsuhiko) who wrote
the code.

Elo


Kontakt Cristian ***@***.***>) kirjutas kuupäeval N, 29.
juuni 2023 kell 14:13:

**Comment by ccruizm** [comment]
Thank you very much Elo, for your speedy reply. I'll contact them, and fingers crossed they still have it. :)

**Comment by ccruizm** [comment]
Hello Elo,

Sorry to bother you again, but my efforts to contact the people you suggested have been unsuccessful (I have not received a reply after several weeks). Could you please contact them and see whether they could share the code?

It would be of great help! Thank you in advance

**Comment by elo073** [comment]
Kontakt Cristian ***@***.***>) kirjutas kuupäeval K, 12.
juuli 2023 kell 12:32:

**Comment by ccruizm** [comment]
Hello Elo,

I still have not heard from your colleagues. Did you have any luck trying to reach them?
